

export const NavBar = () => {
  return (
    <div className="nav-bar">
      <h1>NavBar</h1>
    </div>
  );
};


// Generated by CodiumAI

describe('NavBar', () => {

    // None
    it('should render a h1 element with text \'NavBar\'', () => {
      const wrapper = shallow(<NavBar />);
      expect(wrapper.find('h1').text()).toEqual('NavBar');
    });
});
